export const ApiContract = {
  version: "v1",
  basePath: "/v1",
  routes: {
    health: "/health",
    readiness: "/health/ready",
    currentUser: "/me",
    currentProfile: "/profiles/me",
    openApi: "/openapi.json",
    docs: "/docs",
    businessCategories: "/business-categories",
    businessCategoryRequirements:
      "/business-categories/:categoryId/document-requirements",
    businessApplications: "/business-applications",
    businessApplicationById: "/business-applications/:id",
    businessApplicationBranch: "/business-applications/:id/branch",
    businessApplicationSubmit: "/business-applications/:id/submit",
    businessApplicationWithdraw: "/business-applications/:id/withdraw",
    businessApplicationAssignReviewer: "/business-applications/:id/assign-reviewer",
    businessApplicationStartReview: "/business-applications/:id/start-review",
    businessApplicationRequestChanges: "/business-applications/:id/request-changes",
    businessApplicationApprove: "/business-applications/:id/approve",
    businessApplicationReject: "/business-applications/:id/reject",
    businessApplicationDocuments: "/business-applications/:id/documents",
    businessApplicationDocumentById: "/business-applications/:id/documents/:documentId",
    businessApplicationDocumentReview:
      "/business-applications/:id/documents/:documentId/review",
    myBusinessMemberships: "/me/business-memberships",
    businessById: "/businesses/:businessId",
    businessPublic: "/businesses/:businessId/public",
    businessBranches: "/businesses/:businessId/branches",
    businessBranchById: "/businesses/:businessId/branches/:branchId",
    businessBranchMakePrimary:
      "/businesses/:businessId/branches/:branchId/make-primary",
    businessMembers: "/businesses/:businessId/members",
    businessMemberById: "/businesses/:businessId/members/:membershipId",
    businessMemberSuspend:
      "/businesses/:businessId/members/:membershipId/suspend",
    businessMemberRestore:
      "/businesses/:businessId/members/:membershipId/restore",
    businessInvitations: "/businesses/:businessId/invitations",
    businessInvitationById:
      "/businesses/:businessId/invitations/:invitationId",
    businessInvitationAccept: "/business-invitations/:token/accept",
    businessOpeningHours: "/businesses/:businessId/opening-hours",
    businessClosureDates: "/businesses/:businessId/closure-dates",
    businessClosureDateById:
      "/businesses/:businessId/closure-dates/:closureId",
    businessSettings: "/businesses/:businessId/settings",
    serviceCategories: "/service-categories",
    productCategories: "/product-categories",
    vehicleMakes: "/vehicle-makes",
    vehicleModelsByMake: "/vehicle-makes/:makeId/models",
    businessServices: "/businesses/:businessId/services",
    businessServiceById: "/businesses/:businessId/services/:serviceId",
    businessServiceImages: "/businesses/:businessId/services/:serviceId/images",
    businessServiceImageById:
      "/businesses/:businessId/services/:serviceId/images/:imageId",
    businessServiceCompatibility:
      "/businesses/:businessId/services/:serviceId/compatibility",
    businessProducts: "/businesses/:businessId/products",
    businessProductById: "/businesses/:businessId/products/:productId",
    businessProductImages: "/businesses/:businessId/products/:productId/images",
    businessProductImageById:
      "/businesses/:businessId/products/:productId/images/:imageId",
    businessProductCompatibility:
      "/businesses/:businessId/products/:productId/compatibility",
    businessInventory: "/businesses/:businessId/inventory",
    businessProductInventory:
      "/businesses/:businessId/products/:productId/inventory",
    businessProductInventoryAdjust:
      "/businesses/:businessId/products/:productId/inventory/adjust",
    vehicles: "/vehicles",
    vehicleById: "/vehicles/:vehicleId",
    vehicleMakeDefault: "/vehicles/:vehicleId/make-default",
    favorites: "/favorites",
    favoriteByBusinessId: "/favorites/:businessId",
    discoveryBusinesses: "/discovery/businesses",
    discoveryBusinessBySlug: "/discovery/businesses/:slug",
    discoveryBusinessServices: "/discovery/businesses/:slug/services",
    discoveryBusinessProducts: "/discovery/businesses/:slug/products",
    appointments: "/appointments",
    appointmentById: "/appointments/:appointmentId",
    appointmentConfirm: "/appointments/:appointmentId/confirm",
    appointmentReject: "/appointments/:appointmentId/reject",
    appointmentCancel: "/appointments/:appointmentId/cancel",
    appointmentArrive: "/appointments/:appointmentId/arrive",
    appointmentStart: "/appointments/:appointmentId/start",
    appointmentComplete: "/appointments/:appointmentId/complete",
    appointmentNoShow: "/appointments/:appointmentId/no-show",
    businessAppointments: "/businesses/:businessId/appointments",
    businessBranchAppointmentSlots:
      "/businesses/:businessId/branches/:branchId/appointment-slots",
    quotations: "/quotations",
    quotationById: "/quotations/:quotationId",
    quotationView: "/quotations/:quotationId/view",
    quotationAccept: "/quotations/:quotationId/accept",
    quotationReject: "/quotations/:quotationId/reject",
    businessQuotations: "/businesses/:businessId/quotations",
    businessQuotationById: "/businesses/:businessId/quotations/:quotationId",
    businessQuotationIssue: "/businesses/:businessId/quotations/:quotationId/issue",
    businessQuotationRevise: "/businesses/:businessId/quotations/:quotationId/revise",
    businessQuotationCancel: "/businesses/:businessId/quotations/:quotationId/cancel",
    businessAppointmentQuotation:
      "/businesses/:businessId/appointments/:appointmentId/quotation",
    invoices: "/invoices",
    invoiceById: "/invoices/:invoiceId",
    invoiceView: "/invoices/:invoiceId/view",
    invoiceApprove: "/invoices/:invoiceId/approve",
    invoicePayments: "/invoices/:invoiceId/payments",
    payments: "/payments",
    paymentById: "/payments/:paymentId",
    businessInvoices: "/businesses/:businessId/invoices",
    businessInvoiceById: "/businesses/:businessId/invoices/:invoiceId",
    businessInvoiceIssue: "/businesses/:businessId/invoices/:invoiceId/issue",
    businessInvoiceCancel: "/businesses/:businessId/invoices/:invoiceId/cancel",
    businessQuotationInvoice:
      "/businesses/:businessId/quotations/:quotationId/invoice",
    businessAppointmentInvoice:
      "/businesses/:businessId/appointments/:appointmentId/invoice",
    businessPayments: "/businesses/:businessId/payments",
    businessInvoicePayments:
      "/businesses/:businessId/invoices/:invoiceId/payments",
    businessInvoiceCashPayment:
      "/businesses/:businessId/invoices/:invoiceId/payments/cash",
    reviewEligibilities: "/review-eligibilities",
    reviewEligibilityById: "/review-eligibilities/:eligibilityId",
    reviews: "/reviews",
    reviewById: "/reviews/:reviewId",
    reviewReport: "/reviews/:reviewId/report",
    businessReviews: "/businesses/:businessId/reviews",
    businessReviewResponse: "/businesses/:businessId/reviews/:reviewId/response",
    adminReviews: "/admin/reviews",
    adminReviewById: "/admin/reviews/:reviewId",
    adminReviewHide: "/admin/reviews/:reviewId/hide",
    adminReviewRestore: "/admin/reviews/:reviewId/restore",
    adminReviewRemove: "/admin/reviews/:reviewId/remove",
    adminReviewReports: "/admin/review-reports",
    adminReviewReportDismiss: "/admin/review-reports/:reportId/dismiss",
    adminReviewReportAction: "/admin/review-reports/:reportId/action",
    disputes: "/disputes",
    disputeById: "/disputes/:disputeId",
    disputeMessages: "/disputes/:disputeId/messages",
    disputeEvidence: "/disputes/:disputeId/evidence",
    disputeWithdraw: "/disputes/:disputeId/withdraw",
    businessDisputes: "/businesses/:businessId/disputes",
    businessDisputeById: "/businesses/:businessId/disputes/:disputeId",
    businessDisputeMessages: "/businesses/:businessId/disputes/:disputeId/messages",
    businessDisputeEvidence: "/businesses/:businessId/disputes/:disputeId/evidence",
    adminDisputes: "/admin/disputes",
    adminDisputeById: "/admin/disputes/:disputeId",
    adminDisputeAssign: "/admin/disputes/:disputeId/assign",
    adminDisputeRequestCustomer: "/admin/disputes/:disputeId/request-customer",
    adminDisputeRequestBusiness: "/admin/disputes/:disputeId/request-business",
    adminDisputeStartReview: "/admin/disputes/:disputeId/start-review",
    adminDisputeResolve: "/admin/disputes/:disputeId/resolve",
    adminDisputeReject: "/admin/disputes/:disputeId/reject",
    adminDisputeClose: "/admin/disputes/:disputeId/close",
    adminDisputeInternalMessages: "/admin/disputes/:disputeId/internal-messages",
  },
} as const;

export type ApiRouteKey = keyof typeof ApiContract.routes;
